# Autogenerated wrapper script for Tk_jll for armv7l-linux-gnueabihf
export libtk, wish

using Tcl_jll
using Xorg_libXft_jll
JLLWrappers.@generate_wrapper_header("Tk")
JLLWrappers.@declare_library_product(libtk, "libtk8.6.so")
JLLWrappers.@declare_executable_product(wish)
function __init__()
    JLLWrappers.@generate_init_header(Tcl_jll, Xorg_libXft_jll)
    JLLWrappers.@init_library_product(
        libtk,
        "lib/libtk8.6.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        wish,
        "bin/wish8.6",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
