# Autogenerated wrapper script for Tk_jll for i686-w64-mingw32
export libtk, wish

using Tcl_jll
JLLWrappers.@generate_wrapper_header("Tk")
JLLWrappers.@declare_library_product(libtk, "tk86.dll")
JLLWrappers.@declare_executable_product(wish)
function __init__()
    JLLWrappers.@generate_init_header(Tcl_jll)
    JLLWrappers.@init_library_product(
        libtk,
        "bin\\tk86.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        wish,
        "bin\\wish86.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
